### ISSUE TITLE
[BUG]xboard设置邮箱验证后无法正常发件

### ISSUE THREAD

**Issue by Weoworks** [cedar2025/Xboard#10]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
--------
v1.0.0

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
xboard的邮箱验证设置完成后点击发送测试邮件无法正常发送，就一直转圈，前端发送邮件验证码显示发送成功

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
NOPE，没有报错...就硬在那儿转圈

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
```
#0 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(45): Illuminate\Foundation\Application->abort()
#1 /www/wwwroot/xb/app/Http/Controllers/V1/User/OrderController.php(191): abort()
#2 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\V1\User\OrderController->checkout()
#3 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#4 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\Routing\ControllerDispatcher->dispatch()
#5 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#6 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\Routing\Route->run()
#7 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#8 /www/wwwroot/xb/app/Http/Middleware/User.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#9 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\Http\Middleware\User->handle()
#10 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#12 /www/wwwroot/xb/app/Http/Middleware/Language.php(15): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\Http\Middleware\Language->handle()
#14 /www/wwwroot/xb/app/Http/Middleware/ForceJson.php(20): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#15 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\Http\Middleware\ForceJson->handle()
#16 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Routing/Router.php(800): Illuminate\Pipeline\Pipeline->then()
#18 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\Routing\Router->runRouteWithinStack()
#19 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\Routing\Router->runRoute()
#20 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\Routing\Router->dispatchToRoute()
#21 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch()
#22 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#23 /www/wwwroot/xb/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#25 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#27 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#28 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#30 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#31 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#33 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#35 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#37 /www/wwwroot/xb/app/Http/Middleware/CORS.php(18): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\Http\Middleware\CORS->handle()
#39 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#40 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then()
#41 /www/wwwroot/xb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#42 /www/wwwroot/xb/start.php(29): Illuminate\Foundation\Http\Kernel->handle()
#43 /www/wwwroot/xb/webman.php(20): run()
#44 /www/wwwroot/xb/vendor/workerman/workerman/Connection/TcpConnection.php(646): {closure}()
#45 [internal function]: Workerman\Connection\TcpConnection->baseRead()
#46 /www/wwwroot/xb/vendor/workerman/workerman/Events/Event.php(193): EventBase->loop()
#47 /www/wwwroot/xb/vendor/workerman/workerman/Worker.php(1635): Workerman\Events\Event->loop()
#48 /www/wwwroot/xb/vendor/workerman/workerman/Worker.php(1426): Workerman\Worker::forkOneWorkerForLinux()
#49 /www/wwwroot/xb/vendor/workerman/workerman/Worker.php(1400): Workerman\Worker::forkWorkersForLinux()
#50 /www/wwwroot/xb/vendor/workerman/workerman/Worker.php(560): Workerman\Worker::forkWorkers()
#51 /www/wwwroot/xb/webman.php(23): Workerman\Worker::runAll()
#52 {main}  

```

其他信息：使用的outlook作为邮局且队列服务正常运行，很玄学的一个bug
![image](https://github.com/cedar2025/Xboard/assets/108215869/b27fece8-c14b-4fe3-837f-dffd68ee07c1)
![image](https://github.com/cedar2025/Xboard/assets/108215869/88de563f-a239-4c60-a494-ffc9abf8a1a4)
![image](https://github.com/cedar2025/Xboard/assets/108215869/16cad565-4f16-43e4-a09c-1201806cdfc6)

**Comment by wsw54188** [comment]
我也发现了相同问题
