### ISSUE TITLE
[BUG] 无法自动备份数据库

### ISSUE THREAD

**Issue by linusxiong** [cedar2025/Xboard#151]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号(git commit id)
f099cf6d30ceceba21f389d577d3bdf7a796a6a7
--------

Would you like to deploy using Docker?
你的部署方式（是否为Docker）
Docker
--------

Please briefly describe the issue you encountered (preferably with reproducible steps).
简单描述你遇到的问题（最好带上复现步骤）

数据库备份失败，已经填写了从谷歌获取的OAuth2的配置文件路径和储存桶名称
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
```
[2024-06-15 00:00:04] local.ERROR: 😔：数据库备份失败 
Spatie\DbDumper\Exceptions\DumpFailed: The dump process failed with a none successful exitcode.
Exitcode
========
2: Misuse of shell builtins

Output
======
<no output>

Error Output
============
mysqldump: Got error: 1045: "Plugin caching_sha2_password could not be loaded: Error loading shared library /usr/lib/mariadb/plugin/caching_sha2_password.so: No such file or directory" when trying to connect
 in /www/vendor/spatie/db-dumper/src/Exceptions/DumpFailed.php:14
Stack trace:
#0 /www/vendor/spatie/db-dumper/src/DbDumper.php(194): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process))
#1 /www/vendor/spatie/db-dumper/src/Databases/MySql.php(161): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), '/www/storage/ba...')
#2 /www/app/Console/Commands/BackupDatabase.php(39): Spatie\DbDumper\Databases\MySql->dumpToFile('/www/storage/ba...')
#3 /www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\BackupDatabase->handle()
#4 /www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 /www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#6 /www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#7 /www/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#8 /www/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call(Array)
#9 /www/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#10 /www/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#11 /www/vendor/symfony/console/Application.php(1096): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /www/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\BackupDatabase), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /www/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /www/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 {main}
```
--------

**Comment by linusxiong** [comment]
初步判断问题为系统中缺少caching_sha2_password.so

**Comment by cedar2025** [comment]
新版已经修复
