### ISSUE TITLE
搭配后端问题

### ISSUE THREAD

**Issue by padoru233** [cedar2025/Xboard#2]
前端面板成功按照教程的docker搭建完成，我想后端使用XrayR，使用域名+端口后连接上面板，显示节点未在线，请问该如何配合哪一种后端使用？

**Comment by rebecca554owen** [comment]
原版xrayr，v2bx或者wyx改版，或者是hysteria docker后端都可以用。

**Comment by cedar2025** [comment]
我们都是支持这些后端的，你可以提供一下搭建步骤（使用的是sqlite还是mysql）和相关的错误日志吗（xrayr错误日志和v2_log数据表中的错误日志）？

**Comment by padoru233** [comment]
> 我们都是支持这些后端的，你可以提供一下搭建步骤（使用的是sqlite还是mysql）和相关的错误日志吗（xrayr错误日志和v2_log数据表中的错误日志）？
  
感谢您的回复，我使用了1Panel面板部署网站和反向代理，数据库是sqlite，同时还用了1Panel自带的Docker Compose安装了Redis  

这是一段xRayR的日志：  

> Nov 21 05:33:25 racknerd-3d6341 systemd[1]: Started XrayR Service.
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]: XrayR 0.9.1 (A Xray backend that supports many panels)
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]: 2023/11/21 05:33:26 Start the panel..
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]: 2023/11/21 05:33:26 Xray Core Version: 1.8.4
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]: 2023/11/21 05:33:26 [Warning] core: Xray 1.8.4 started
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]: 2023/11/21 05:33:26 Panel Start fialed: request http://proxy.wananbubu.xyz/api/v1/server/UniProxy/config failed: {
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]:     "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]: }, <nil>
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]: panic: Panel Start fialed: request http://proxy.wananbubu.xyz/api/v1/server/UniProxy/config failed: {
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]:     "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]: }, <nil>
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]: goroutine 1 [running]:
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]: log.Panicf({0x358c09d?, 0x39d03a0?}, {0xc000731e20?, 0xc0006ef3b0?, 0x2dd6ea0?})
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]:         log/log.go:439 +0x65
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0000c34c0)
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]:         github.com/XrayR-project/XrayR/panel/panel.go:210 +0x5db
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]: main.main()
> Nov 21 05:33:26 racknerd-3d6341 XrayR[162945]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x233
> Nov 21 05:33:26 racknerd-3d6341 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
> Nov 21 05:33:26 racknerd-3d6341 systemd[1]: XrayR.service: Failed with result 'exit-code'.
> Nov 21 05:33:36 racknerd-3d6341 systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 5499.
> Nov 21 05:33:36 racknerd-3d6341 systemd[1]: Stopped XrayR Service.
> Nov 21 05:33:36 racknerd-3d6341 systemd[1]: Started XrayR Service.
> Nov 21 05:33:36 racknerd-3d6341 XrayR[163025]: XrayR 0.9.1 (A Xray backend that supports many panels)
> Nov 21 05:33:36 racknerd-3d6341 XrayR[163025]: 2023/11/21 05:33:36 Start the panel..
> Nov 21 05:33:36 racknerd-3d6341 XrayR[163025]: 2023/11/21 05:33:36 Xray Core Version: 1.8.4
> Nov 21 05:33:36 racknerd-3d6341 XrayR[163025]: 2023/11/21 05:33:36 [Warning] core: Xray 1.8.4 started
> Nov 21 05:33:37 racknerd-3d6341 XrayR[163025]: 2023/11/21 05:33:37 Panel Start fialed: request http://proxy.wananbubu.xyz/api/v1/server/UniProxy/config failed: {
> Nov 21 05:33:37 racknerd-3d6341 XrayR[163025]:     "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
> Nov 21 05:33:37 racknerd-3d6341 XrayR[163025]: }, <nil>
> Nov 21 05:33:37 racknerd-3d6341 XrayR[163025]: panic: Panel Start fialed: request http://proxy.wananbubu.xyz/api/v1/server/UniProxy/config failed: {
> Nov 21 05:33:37 racknerd-3d6341 XrayR[163025]:     "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
> Nov 21 05:33:37 racknerd-3d6341 XrayR[163025]: }, <nil>
> Nov 21 05:33:37 racknerd-3d6341 XrayR[163025]: goroutine 1 [running]:
> Nov 21 05:33:37 racknerd-3d6341 XrayR[163025]: log.Panicf({0x358c09d?, 0x39d03a0?}, {0xc0006e7e20?, 0xc000707440?, 0x2dd6ea0?})
> Nov 21 05:33:37 racknerd-3d6341 XrayR[163025]:         log/log.go:439 +0x65
> Nov 21 05:33:37 racknerd-3d6341 XrayR[163025]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00017b4c0)
> Nov 21 05:33:37 racknerd-3d6341 XrayR[163025]:         github.com/XrayR-project/XrayR/panel/panel.go:210 +0x5db
> Nov 21 05:33:37 racknerd-3d6341 XrayR[163025]: main.main()
> Nov 21 05:33:37 racknerd-3d6341 XrayR[163025]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x233
> Nov 21 05:33:37 racknerd-3d6341 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
> Nov 21 05:33:37 racknerd-3d6341 systemd[1]: XrayR.service: Failed with result 'exit-code'.
  
这是xboard的日志：
  
> 023-11-20 07:41:58,324 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
> 2023-11-20 07:41:58,326 INFO supervisord started with pid 1
> 2023-11-20 07:41:59,329 INFO spawned: 'adapterman' with pid 7
> 2023-11-20 07:41:59,331 INFO spawned: 'cron' with pid 8
> 2023-11-20 07:41:59,332 INFO spawned: 'nginx' with pid 9
> 2023-11-20 07:41:59,335 INFO spawned: 'xboard-queue' with pid 10
> Adapterman v0.6.1 OK
> Workerman[webman.php] start in DEBUG mode
> -------------------------------------------- WORKERMAN --------------------------------------------
> Workerman version:4.1.13          PHP version:8.1.25           Event-Loop:\Workerman\Events\Select
> --------------------------------------------- WORKERS ---------------------------------------------
> proto   user            worker          listen                   processes    status           
> tcp     root            AdapterMan      http://127.0.0.1:7010    2             [OK]            
> ---------------------------------------------------------------------------------------------------
> Press Ctrl+C to stop. Start success.
> 2023-11-20 07:42:00,476 INFO success: adapterman entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2023-11-20 07:42:00,477 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2023-11-20 07:42:00,478 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2023-11-20 07:42:00,478 INFO success: xboard-queue entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)  

不知道是不是套了cdn和ssl的问题

**Comment by cedar2025** [comment]
这个是已只的问题，原版XrayR在对接V2board的时候读取的是v2ray的节点，所以在v2_log中会有报错“server is not exist”, 你可以使用 https://github.com/wyx2685/XrayR 这个改版XrayR规避这个问题。

**Comment by padoru233** [comment]
> 这是已只的问题，原版XrayR在活动V2board的时候读取是v2ray的节点，所以在v2_log中会有报错“服务器可能不存在”，你使用https://github.com/wyx2685/XrayR这个改版XrayR规避了这个问题。

感谢您的回答，已经成功上线服务端了，可以关掉这个issue了

**Comment by padoru233** [comment]
> 这个是已只的问题，原版XrayR在对接V2board的时候读取的是v2ray的节点，所以在v2_log中会有报错“server is not exist”, 你可以使用 https://github.com/wyx2685/XrayR 这个改版XrayR规避这个问题。

又遇到一个新问题，进入登录界面显示白屏，已登录的没有问题  
还有我查看了v2_log，有大量`This database engine does not support JSON contains operations`的报错

**Comment by cedar2025** [comment]
对于This database engine does not support JSON contains operations 这个抱错请升级最新版本 https://github.com/cedar2025/Xboard/commit/cf4462dd82dcfb4f0845f58c2b1c757478fb91d1 在这个commit上已经修复

**Comment by padoru233** [comment]
好的，通过Compose重新部署已经没有报错了，流量统计也显示正常

**Comment by hadimousavi79** [comment]
> hysteria docker backend

hi
Is it possible give a doc that we can use hysteria docker backend with xboard?
Also is it possible tell me what is difference between xboard and V2board wyx2685?

**Comment by vstar37** [comment]
> wyx本身就是为了适配xb的，面板类型改成NewV2board
> 
> > > 原版xrayr，v2bx或者wyx改版，或者是hysteria docker后端都可以用。
> > 
> > 
> > 想请教下如何从wyx版本迁移到xboard?

主要想知道数据库怎么从wyx的面板迁移到xboard
