### ISSUE TITLE
[BUG]debian11系统使用Docker Compose纯命令行部署出错，同样的方法使用ubntun20.04系统部署正常

### ISSUE THREAD

**Issue by sky22333** [cedar2025/Xboard#89]
### debian11系统使用Docker Compose纯命令行部署出错，同样的方法使用ubntun20.04系统部署正常，新系统没有部署任何其他的服务，容器日志如下：

```
Workerman[webman.php] start in DEBUG mode
stream_socket_server(): Unable to connect to tcp://127.0.0.1:7010 (Address not available) in file /www/vendor/workerman/workerman/Worker.php on line 2363
PHP Fatal error:  Uncaught Exception: Address not available in /www/vendor/workerman/workerman/Worker.php:2365
Stack trace:
#0 /www/vendor/workerman/workerman/Worker.php(700): Workerman\Worker->listen()
#1 /www/vendor/workerman/workerman/Worker.php(555): Workerman\Worker::initWorkers()
#2 /www/webman.php(23): Workerman\Worker::runAll()
#3 {main}
  thrown in /www/vendor/workerman/workerman/Worker.php on line 2365

Fatal error: Uncaught Exception: Address not available in /www/vendor/workerman/workerman/Worker.php:2365
Stack trace:
#0 /www/vendor/workerman/workerman/Worker.php(700): Workerman\Worker->listen()
#1 /www/vendor/workerman/workerman/Worker.php(555): Workerman\Worker::initWorkers()
#2 /www/webman.php(23): Workerman\Worker::runAll()
#3 {main}
  thrown in /www/vendor/workerman/workerman/Worker.php on line 2365
2024-03-13 13:43:13,501 INFO success: adapterman entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-03-13 13:43:13,502 WARN exited: adapterman (exit status 255; not expected)
root@:~/Xboard# 
```

**Comment by v2less** [comment]
是否启用Sqlite(无需额外安装)代替Mysql ───────────────────────┐
 │ 启用                                                         │
 └──────────────────────────────────────────────────────────────┘

sqlite创建失败
